export const ActionTypes = {
    SET_USER : "SET_USER",
    SET_TOKEN : "SET_TOKEN",
    SET_FEATURED_PLAYLISTS: "SET_FEATURED_PLAYLISTS",
    SET_NEW_RELEASES: "SET_NEW_RELEASES",
    SET_TIMELINE_ALBUMS: "SET_TIMELINE_ALBUMS",
    SET_USER_LIKED_SONGS: "SET_USER_LIKED_SONGS",
    SET_SELECTED_ALBUM: "SET_SELECTED_ALBUM",
    REMOVE_SELECTED_ALBUM : "REMOVE_SELECTED_ALBUM",
    SET_USER_OWNED_PLAYLISTS: "SET_USER_OWNED_PLAYLISTS",
    SET_SELECTED_PLAYLIST: "SET_SELECTED_PLAYLIST",
    REMOVE_SELECTED_PLAYLIST : "REMOVE_SELECTED_PLAYLIST",
    
};